version: '3'

services:
  database:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Events
    networks:
      - backend_db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '80:8080'
    depends_on:
      - database
    security_opt:
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    environment:
      DB_HOST_NAME: database
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: Events
    networks:
      - backend_db
      - frontend-api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    container_name: event-frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend-api

networks:
  backend_db:
  frontend-api:
