version: '3'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Events
    networks:
      - backend_db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - database
    security_opt:
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: Events
    networks:
      - backend_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    container_name: event-frontend
    ports:
      - '5173:5173'
    environment:
      VITE_API_URL: http://localhost:8080
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  backend_db:
