apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/software-containerization-backend-db: "true"
        component: api
    spec:
      containers:
        - env:
          - name: DB_HOST_NAME
            value: database-cluster-ip-service
          - name: DB_NAME
            value: Events
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: password
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: userName

          image: rawalsaadi/soft_containerization-api:latest
          name: api
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: 
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
      restartPolicy: Always
status: {}
