apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    component: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: development
            - name: VITE_API_URL
              value: api-cluster-ip-service
          image: ghcr.io/noleu/event_calendar_frontend
          name: event-frontend
          ports:
            - containerPort: 80
          resources: 
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 384Mi
            
      restartPolicy: Always
status: {}
