apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    component: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: development
            - name: VITE_API_URL
              value: http://localhost:8080
          image: ghcr.io/noleu/event_calendar_frontend
          name: event-frontend
          ports:
            - containerPort: 5173
              hostPort: 5173
              protocol: TCP
          resources: 
            requests:
              cpu: 1
              memory: 256Mi
            limits:
              cpu: 2
              memory: 768Mi
            
      restartPolicy: Always
status: {}
