apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "helmcharts.fullname" . }}-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "helmcharts.fullname" . }}-api
  minReplicas: {{ .Values.apiHpa.minReplicas }}
  maxReplicas: {{ .Values.apiHpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.apiHpa.averageUtilization }}