apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "helmcharts.fullname" . }}-app-developer-role
  labels:
  {{- include "helmcharts.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - /
  - extensions
  - apps
  resources:
  - deployments
  - services
  - pods
  - configmaps
  - pods/log
  - pods/exec
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helmcharts.fullname" . }}-app-developer-binding
  labels:
  {{- include "helmcharts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "helmcharts.fullname" . }}-app-developer-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "helmcharts.fullname" . }}-app-developer'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helmcharts.fullname" . }}-app-developer
  labels:
  {{- include "helmcharts.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.appDeveloper.serviceAccount.annotations | nindent 4 }}