apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helmcharts.fullname" . }}-db-configmap
  labels:
    {{- include "helmcharts.labels" . | nindent 4 }}
data:
  db_host: {{ printf "%s-%s" (include "helmcharts.fullname" .) .Values.dbConfigmap.dbHost | quote }}
  db_name: {{ .Values.dbConfigmap.dbName | quote }}
