apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmcharts.fullname" . }}-frontend
  labels:
    {{- include "helmcharts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
    {{- include "helmcharts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: frontend
      {{- include "helmcharts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              key: api_url
              name: {{ include "helmcharts.fullname" . }}-frontend-configmap
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        name: my-app-event-frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}
        ports:
          - containerPort: {{ .Values.frontend.containerPort }}
        resources: {{- toYaml .Values.frontend.resources | nindent 10 }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmcharts.fullname" . }}-frontend-cluster-ip-service
  labels:
    {{- include "helmcharts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontendClusterIpService.type }}
  selector:
    app: frontend
  {{- include "helmcharts.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.frontendClusterIpService.ports | toYaml | nindent 2 -}}
