apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "helmcharts.fullname" . }}-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "helmcharts.fullname" . }}-frontend
  minReplicas: {{ .Values.frontendHpa.minReplicas }}
  maxReplicas: {{ .Values.frontendHpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontendHpa.averageUtilization}}