apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-app-app-developer-role
  namespace: default
rules:
  - apiGroups: ["","/","extensions", "apps"]
    resources: ["deployments", "services", "pods", "configmaps", "pods/log", "pods/exec" ]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-app-app-developer-binding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: my-app-app-developer-role
subjects:
- kind: ServiceAccount
  name: app-developer
  apiGroup: ""

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-developer
  namespace: default
