apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    component: database
  name: my-app-database
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/software-containerization-backend-db: "true"
        component: database
    spec:
      volumes:
        - name: db-data-storage
          persistentVolumeClaim:
            claimName: my-app-db-pvc-claim0
      containers:
        - name: database
          image: postgres:16
          ports:
            - containerPort: 5432
              protocol: TCP

          env:
            - name: POSTGRES_DB
              valueFrom: 
                configMapKeyRef:
                  name: my-app-db-configmap
                  key: db_name
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-db-secrets
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-app-db-secrets
                  key: username

          volumeMounts:
            - name: db-data-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-database-cluster-ip-service
  namespace: default
spec:
  selector:
    component: database
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  