apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: database
  name: my-app-db-pvc-claim0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
