# needs 'kubectl apply -f https://k8s.io/examples/pods/inject/secret.yaml '
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  labels:
    component: db
  namespace: default
data:
 username: cG9zdGdyZXM=
 password: cG9zdGdyZXM=