apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    component: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: node_env
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: api_url
          image: ghcr.io/noleu/event_calendar_frontend
          name: event-frontend
          ports:
            - containerPort: 80
          resources: 
            requests:
              cpu: 1
              memory: 256Mi
            limits:
              cpu: 2
              memory: 768Mi
            
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-cluster-ip-service
spec:
  selector:
    component: frontend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: k8-load-balancer-service
spec:
  selector:
    component: frontend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
