apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: event-frontend
          image: https://ghcr.io/noleu/event_calendar_frontend
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: node_env
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: api_url

          ports:
            - containerPort: 80
          resources: 
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 384Mi
            
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-cluster-ip-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend
