apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: event-frontend
          image: ghcr.io/noleu/event_calendar_frontend:latest
          ports:
            - containerPort: 80
          resources: 
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 384Mi
            
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-frontend-cluster-ip-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend
