apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
#  name: frontend-developer
  name: infrastructure-admin
  namespace: default
rules:
  - apiGroups: ["", "/", "extensions", "apps", "networking.k8s.io", "networking.gke.io"]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    resources:
      - configmaps
      - ingresses
      - managedcertificates
      - networkpolicies
      - persistentvolumeclaims
      - services

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infrastructure-admin-binding
  namespace: default
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: infrastructure-admin
subjects:
- kind: ServiceAccount
  name: test-sa
#  name: cluster-user-2@software-containerization-2024.iam.gserviceaccount.com
#  apiGroup: rbac.authorization.k8s.io
  apiGroup: ""
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: infrastructure-admin
  namespace: default