apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: default
spec:
  tls:
    - hosts:
      - myeventsapp.com
      secretName: tls-secret
  rules:
  - host: myeventsapp.com
    http:
      paths:
      - pathType: Prefix
        path: "/?(.*)"
        backend:
          service: 
            name: frontend-cluster-ip-service
            port: 
              number: 80