apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: event-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: public
  rules:
  - host: myeventsapp.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-cluster-ip-service
            port: 
              number: 80
  tls:
  - hosts:
    - myeventsapp.com
    secretName: myingress-cert