api:
  containerSecurityContext:
    capabilities:
      add:
      - SYS_PTRACE
  image:
    repository: ghcr.io/noleu/event_calendar_api
    tag: latest
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  containerPort: 80
  replicas: 1
apiClusterIpService:
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
appDeveloper:
  serviceAccount:
    annotations: {}
database:
  image:
    repository: postgres
    tag: "16"
  replicas: 1
  containerPort: 5432
databaseClusterIpService:
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
dbConfigmap:
  dbHost: database-cluster-ip-service
  dbName: Events
dbSecrets:
  password: ""
  username: ""
frontend:
  image:
    repository: ghcr.io/noleu/event_calendar_frontend
    tag: latest
  resources:
    limits:
      cpu: 500m
      memory: 384Mi
    requests:
      cpu: 250m
      memory: 128Mi
  replicas: 1
  containerPort: 80
frontendClusterIpService:
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
infrastructureAdmin:
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
pvc:
  dbPvcClaim0:
    storageRequest: 500Mi
