api:
  containerSecurityContext:
    capabilities:
      add:
      - SYS_PTRACE
  image:
    repository: ghcr.io/noleu/event_calendar_api
    tag: v1
  containerPort: 80
  replicas: 1
apiClusterIpService:
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
appDeveloper:
  serviceAccount:
    annotations: {}
database:
  image:
    repository: postgres
    tag: "16"
  replicas: 1
  containerPort: 5432
databaseClusterIpService:
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
dbConfigmap:
  dbHost: database-cluster-ip-service
  dbName: Events
dbSecrets:
  password: "cG9zdGdyZXM="
  username: "cG9zdGdyZXM="
frontend:
  image:
    repository: ghcr.io/noleu/event_calendar_frontend
    tag: v1
  replicas: 3
  containerPort: 80
  canary:
    replicas: 0
    image:
      repository: ghcr.io/noleu/event_calendar_frontend
      tag: canary
frontendClusterIpService:
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
frontendConfigmap:
  apiUrl: api-cluster-ip-service
infrastructureAdmin:
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
pvc:
  createPVC: true
  dbPvcClaim0:
    storageRequest: 500Mi
apiHpa:
  maxReplicas: 8
  minReplicas: 1
  averageUtilization: 50
frontendHpa:
  maxReplicas: 6
  minReplicas: 1
  averageUtilization: 50

caCertificate:
  enabled: true
  commonName: "My CA"
  isCA: true
  subject:
    countries:
      - "Netherlands"
    localities:
      - "Amsterdam"
    organizations:
      - "VU"
    organizationalUnits:
      - "CS"

selfSignedIssuer:
  enabled: true

networkPolicies:
  denyExternalDbAccess:
    enabled: false
    name: deny-external-db-access
    podSelectorLabels:
      component: database
    policyTypes:
      - Ingress
    ingress: []

  allowApiToDb:
    enabled: false
    name: allow-api-to-db
    podSelectorLabels:
      component: database
    policyTypes:
      - Ingress
    ingress:
      - from:
          - podSelector:
              matchLabels:
                component: api
        ports:
          - protocol: TCP
            port: 5432

  allowFrontendToApi:
    enabled: false
    name: allow-frontend-to-api
    podSelectorLabels:
      component: api
    policyTypes:
      - Ingress
    ingress:
      - from:
          - podSelector:
              matchLabels:
                app: frontend
        ports:
          - protocol: TCP
            port: 80 