apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
  namespace: default
spec:
  isCA: true
  commonName: "My CA"
  secretName: ca-certificate-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  subject:
    countries: 
      - "Netherlands"
    localities:
      - "Amsterdam"
    organizations:
      - "VU"
    organizationalUnits:
      - "CS"
