apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "myapp.fullname" . }}-ingress-service
  labels:
  {{- include "myapp.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: managed-cert
spec:
  ingressClassName: nginx
  rules:
  - host: myeventsapp.com
    http:
      paths:
      - backend:
          service:
            name: '{{ include "myapp.fullname" . }}-frontend-cluster-ip-service'
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - myeventsapp.com
    secretName: myingress-cert