apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    component: api
spec:
  containers:
  - name: api
    image: ghcr.io/noleu/event_calendar_api:latest
    ports:
      - containerPort: 8080