apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/software-containerization-backend-db: "true"
        io.kompose.service: api
    spec:
      containers:
        - args:
            - /dlv
            - --headless
            - --listen=:40000
            - --api-version=2
            - exec
            - /server
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@database:5432/postgres
          image: ghcr.io/noleu/event_calendar_api
          name: api
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
            - containerPort: 40000
              hostPort: 40000
              protocol: TCP
          resources: 
            requests:
              cpu: 1
              memory: 0.5gb
            limits:
              cpu: 2
              memory: 3gb
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
      restartPolicy: Always
status: {}
