apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: database
  name: database-pvc-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
