apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/software-containerization-backend-db: "true"
        io.kompose.service: database
    spec:
      volumes:
        - name: db_data_storage
          persistentVolumeClaim:
            - claimName: database-data-persistentVolumeClaim
      containers:
        - env:
            - name: POSTGRES_DB
              value: Events
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: userName

          image: postgres:16
          name: database
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: 
            requests:
              cpu: 1
              memory: 2gb
            limits:
              cpu: 2
              memory: 4gb
      restartPolicy: Always
status: {}
