apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/software-containerization-default: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: development
            - name: VITE_API_URL
              value: http://localhost:8080
          image: frontend
          name: event-frontend
          ports:
            - containerPort: 5173
              hostPort: 5173
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: frontend-claim0
            - mountPath: /app/node_modules
              name: frontend-claim1
      restartPolicy: Always
      volumes:
        - name: frontend-claim0
          persistentVolumeClaim:
            claimName: frontend-claim0
        - name: frontend-claim1
          persistentVolumeClaim:
            claimName: frontend-claim1
status: {}
