apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "frontend-svc-port"
      protocol: TCP
      port: 5173
      targetPort: frontend-svc
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
