version: "3"

services:
  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
  api:
    build:
        context: ./api
        dockerfile: debug.Dockerfile
    ports:
      - "8080:8080"
      - "40000:40000"
    depends_on:
      - database
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    command: /dlv --headless --listen=:40000 --api-version=2 exec /server
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/postgres
